<?php

function dumbauth_menu() {
  $items['dumbauth'] = array(
    'access callback' => 'has_token',
    'page callback' => 'do_dumbauth',
    'delivery callback' => 'drupal_json_output',
  );

  $items['admin/config/services/dumbauth'] = array(
    'title' => 'Dumb Auth',
    'description' => 'Settings for the Dumb Auth module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dumbauth_admin'),
    'access arguments' => array('administer dumbauth settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function has_token() {
  return isset($_SERVER['HTTP_X_DUMBAUTH_TOKEN']) && $_SERVER['HTTP_X_DUMBAUTH_TOKEN'] === variable_get('dumbauth_token');
}

function do_dumbauth() {
  if($uid = user_authenticate($_POST['username'], $_POST['password'])) {
    return user_load($uid);
  }

  return FALSE;
}

function dumbauth_admin() {
  $form = array();

  $form['dumbauth_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Authentication token'),
    '#default_value' => variable_get('dumbauth_token'),
    '#size' => 36,
    '#description' => t('A unique string that must be sent in the X-DumbAuth-Token header'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
